export const types = {
    OPEN_MODAL: "SHOW_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
    SHOW_CITIES: "SHOW_CITIES",
    SHOW_GUEST_FILTERS: "SHOW_GUEST_FILTERS",
    CHOOSE_LOCATION: "CHOOSE_LOCATION",
    CHOOSE_TOTAL_GUESTS: "CHOOSE_TOTAL_GUEST",
    SET_LOCATION: "SET_LOCATION",
    SET_GUESTS: "SET_GUESTS",
    INCREMENT_ADULTS: "INCREMENT_ADULTS",
    DECREMENT_ADULTS: "DECREMENT_ADULTS",
    INCREMENT_CHILDREN: "INCREMENT_CHILDREN",
    DECREMENT_CHILDREN: "DECREMENT_CHILDREN",
}